before_script:
- "git submodule update --init --recursive"
script: "phantomjs lib/phantom-jasmine/lib/run_jasmine_test.coffee tests/index.html"
notifications:
  irc:
    channels:
      - "irc.freenode.org#patterns"
    on_success: always
    on_failure: always
